### ISSUE TITLE
token怎样设置

### ISSUE THREAD

**Issue by huangpiqiao** [kidneyleung/egg-consul-client#1]
请问一下如果需要设置token的话，应该放在配置参数哪里？

**Comment by khronosleung** [comment]
尝试这样配置：

```js
config.consul = {
  server: {
    // ...
    defaults: {
        token: '123'
    }
  },
  client: {
    // ....
  },
};


```

node-consul文档：
https://github.com/silas/node-consul#consuloptions

node-consul用例参考：
https://github.com/silas/node-consul/blob/main/test/consul.js
